[tool.black]
line-length = 120
target-version = ['py312']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
line_length = 120

[tool.mypy]
strict = false
ignore_missing_imports = true
exclude = 'src/old/.*'

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q --disable-warnings"
testpaths = ["src"]
python_files = ["code_tests.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
